version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "omarcarreon"
    assignees:
      - "omarcarreon"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "openpyxl"
        update-types: ["version-update:semver-major"]
      - dependency-name: "lxml"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "omarcarreon"
    assignees:
      - "omarcarreon"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for Python packages in pyproject.toml
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "develop"
    open-pull-requests-limit: 5
    reviewers:
      - "omarcarreon"
    assignees:
      - "omarcarreon"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "dev-dependencies"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "pytest"
        update-types: ["version-update:semver-major"]
      - dependency-name: "black"
        update-types: ["version-update:semver-major"]
      - dependency-name: "flake8"
        update-types: ["version-update:semver-major"] 